import AppKit
import DokrCore

/// Starts/stops the resident folder helpers.
enum FolderLauncher {
    static let indicatorsDefaultsKey = "showFolderIndicators"

    static var indicatorsEnabled: Bool {
        UserDefaults.standard.object(forKey: indicatorsDefaultsKey) as? Bool ?? true
    }

    /// Bundle URLs of the docked folders, as generated by `FolderBundleBuilder`.
    static func dockedBundles(for folders: [AppFolder]) -> [URL] {
        let names = AppFolder.bundleNames(for: folders)
        return folders
            .filter(\.showInDock)
            .compactMap { names[$0.id] }
            .map { FolderStore.foldersDirectory.appendingPathComponent("\($0).app", isDirectory: true) }
            .filter { FileManager.default.fileExists(atPath: $0.path) }
    }

    /// Launches docked folder helpers in the background (no popup), skipping running ones.
    static func launchHelpers(for folders: [AppFolder]) {
        let running = Set(NSWorkspace.shared.runningApplications.compactMap { $0.bundleURL?.standardizedFileURL.path })
        for bundle in dockedBundles(for: folders) where !running.contains(bundle.standardizedFileURL.path) {
            let process = Process()
            process.executableURL = URL(fileURLWithPath: "/usr/bin/open")
            process.arguments = ["-g", bundle.path, "--args", "--background"]
            try? process.run()
            process.waitUntilExit()
        }
    }

    static func terminateRunningHelpers() {
        let helpers = NSWorkspace.shared.runningApplications.filter {
            $0.bundleIdentifier?.hasPrefix(AppFolder.bundleIdentifierPrefix) == true
        }
        guard !helpers.isEmpty else { return }
        helpers.forEach { $0.terminate() }

        let deadline = Date().addingTimeInterval(2)
        while helpers.contains(where: { !$0.isTerminated }), Date() < deadline {
            RunLoop.current.run(until: Date().addingTimeInterval(0.05))
        }
        helpers.filter { !$0.isTerminated }.forEach { $0.forceTerminate() }
    }
}

/// ~/Library/LaunchAgents entry that runs `Dokr --launch-folders` at login, so folder
/// helpers are up (and show their dots) without opening Dokr.
enum LoginAgent {
    static let label = "com.seifeldeenessam.dokr.folders"

    static var url: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/LaunchAgents/\(label).plist")
    }

    static func install() throws {
        guard let executable = Bundle.main.executablePath else { return }
        let plist: [String: Any] = [
            "Label": label,
            "ProgramArguments": [executable, "--launch-folders"],
            "RunAtLoad": true,
            "LimitLoadToSessionType": "Aqua",
        ]
        let data = try PropertyListSerialization.data(fromPropertyList: plist, format: .xml, options: 0)
        // Rewrite only when it changes (e.g. Dokr moved) to avoid repeated "Background Items" alerts.
        if (try? Data(contentsOf: url)) == data { return }
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: url, options: .atomic)
    }

    static func uninstall() {
        try? FileManager.default.removeItem(at: url)
    }
}
